const days=[
{date:'9/17（四）',title:'抵達南城，先吃再睡',theme:'今天只做必要的事：領車、吃飯、入住。',map:'吉野家 那覇東バイパス国場店',directions:'https://www.google.com/maps/dir/?api=1&origin=那覇空港&destination=沖縄県南城市知念海野&waypoints=吉野家+那覇東バイパス国場店&travelmode=driving',lede:'第一晚不用趕行程。吃飽、洗澡、早點睡，明天才有精神往北開。',stops:[['19:30','吉野家 鰻重','吉野家 那覇東バイパス国場店','日本吉野家全年都有鰻重。剛下飛機不想等候，這一餐最快也最穩。',['24 小時','有停車位']],['21:00','入住 Umino24','沖縄県南城市知念海野','今晚只需要記得一件事：明天早上從東岸看海。',['整棟 3 房','早上看日出']]],notes:['領行李約 30 分鐘。','租車接駁與手續預留 40-60 分鐘。台灣駕照正本、日文譯本正本、護照與主駕信用卡都要帶。']},
{date:'9/18（五）',title:'北部看海，晚上吃石垣牛',theme:'北部車程長。景點寧可少一點，也要留時間走路與看海。',map:'沖縄美ら海水族館',directions:'https://www.google.com/maps/dir/?api=1&origin=沖縄県南城市知念海野&destination=石垣牛専門店+焼肉金城+北谷本店&waypoints=沖縄美ら海水族館|備瀬のフクギ並木|古宇利島&travelmode=driving',lede:'今天的重點是水族館、福木林道、古宇利島與石垣牛。不要再多塞景點。',stops:[['10:40','美麗海水族館','沖縄美ら海水族館','先去黑潮之海大水槽，找位置坐下來看鯨鯊。館內午餐簡單吃，把胃留給晚餐。',['停留約 3 小時','園內午餐']],['14:45','備瀨福木林道','備瀬のフクギ並木','老福木把路遮成綠色隧道。慢慢走 30 分鐘就好，不需要趕完整圈。',['免費','可搭水牛車']],['16:10','古宇利島','古宇利大橋與古宇利海灘','橋下的海色很漂亮。風大時不必繞島，停在海灘看橋就值得。',['日落約 18:45','可踩水']],['19:15','燒肉 金城','石垣牛専門店 焼肉 金城 北谷本店','這一餐吃石垣牛。點拼盤就能同時吃到油花多與赤身部位。',['已訂 4 位','免費停車']]],notes:['南城到北部單程約 2 小時，過路費約 ¥1,000。','新垣ぜんざい屋可作為水族館後的刨冰加點，週一公休。','回程餓了可去 A&W 名護店，沖繩限定的麥根沙士值得試。']},
{date:'9/19（六）',title:'琉球王國，最後一塊牛排',theme:'上午走聖地與王城，傍晚到瀨長島看飛機。',map:'斎場御嶽',directions:'https://www.google.com/maps/dir/?api=1&origin=斎場御嶽&destination=ジャッキーステーキハウス&waypoints=首里城公園|瀬長島ウミカジテラス&travelmode=driving',lede:'御嶽慢慢走，首里城慢慢看。傍晚只要坐在瀨長島等飛機飛過。',stops:[['10:10','齋場御嶽','斎場御嶽','琉球王國最重要的聖地。地面石板可能濕滑，穿好走的鞋，放低音量慢慢走。',['步道約 40 分','先購票']],['13:45','首里城公園','首里城公園・守禮門','從守禮門往上走，可以看見琉球王國的紅瓦與重建中的正殿。',['守禮門免費','紅瓦建築']],['16:45','瀨長島','瀬長島ウミカジテラス','白色階梯面向機場跑道。找個位置坐著吃鬆餅，等飛機低空進場。',['日落約 18:45','看飛機']],['19:00','Jack’s Steak House','ジャッキーステーキハウス','沖繩老牌牛排店。不能訂位，先去登記，等候期間可以在附近走走。',['人均約 ¥2,000','需要排隊']]],notes:['安座真海灘離住處近，早上若有空可去踩水 20 分鐘。','齋場御嶽門票要先到南城市地域物産館買。','首里城正殿開放時間可能調整，出發前請再確認。']},
{date:'9/20（日）',title:'吃碗沖繩麵，回家',theme:'退房後往機場走，今天不安排額外景點。',map:'そば処 玉家 大里店',directions:'https://www.google.com/maps/dir/?api=1&origin=そば処+玉家+大里店&destination=那覇空港&travelmode=driving',lede:'沖繩麵當這趟旅行的最後一餐。吃完加油、還車，平穩地去機場。',stops:[['10:00','そば處 玉家','そば処 玉家 大里店','沖繩麵是全小麥麵條配柴魚豬骨湯。桌上的艾草可先加一點試味道。',['10:00 開門','回機場順路']]],notes:['09:15 退房，垃圾分類與鑰匙依 Airbnb 訊息處理。','滿油還車。還車與接駁到航廈預留 30 分鐘。','11:55 國際線報到，13:25 IT797 起飛。']}
];
const $=s=>document.querySelector(s);const navigate=q=>'https://www.google.com/maps/dir/?api=1&destination='+encodeURIComponent(q)+'&travelmode=driving';const photos={'備瀨福木林道':'https://www.japanican.com/wp-content/uploads/2023/04/okinawa_Fukugi-trees-in-Bise_110212.jpg','古宇利島':'https://www.knt.co.jp/meito/images/korijima_mv.jpg','齋場御嶽':'https://okayamakajyu.com/images/98other/okinawa/meisyo/sefar/sefar04.jpg','首里城公園':'https://www.okinawastory.jp/files/attractions/000/001/074/images_OnQwuQMUjAktT7O9L4HMJ7fDHTidSkc1nvyLeWRO-w1300.jpg'};const facts={'備瀨福木林道':'福木是沖繩聚落對抗颱風的傳統防風樹。備瀨的樹與民宅共同形成聚落格局，部分老樹超過 300 年。','古宇利島':'古宇利大橋於 2005 年通車，全長約 1,960 公尺，讓島嶼從船運時代進入自駕可抵達的旅遊路線。','齋場御嶽':'齋場御嶽是琉球王國最高等級的祭祀場所。王國時代，國王與神職人員會在此進行國家級儀式。','首里城公園':'首里城曾是琉球王國的政治與外交中心。守禮門牌匾上的「守禮之邦」象徵以禮相待的琉球精神。'};
function render(i){const d=days[i];document.querySelectorAll('.day-btn').forEach((b,n)=>b.setAttribute('aria-selected',n===i));$('#folio').textContent=d.date;$('#dayTitle').textContent=d.title;$('#dayTheme').textContent=d.theme;$('#lede').textContent=d.lede;$('#map').innerHTML=`<div><span>今日主要目的地</span><strong>${d.map}</strong></div>`;$('#features').innerHTML=d.stops.map((s,n)=>`<article class="feature">${photos[s[1]]?`<img class="spot-photo" src="${photos[s[1]]}" alt="${s[1]} 實景照片">`:''}<div class="feature-meta"><span>${s[0]}</span><span>第 ${n+1} 站</span></div><h3>${s[1]}<small>${s[2]}</small></h3><p>${s[3]}</p>${facts[s[1]]?`<details class="more"><summary>歷史與特色</summary><p>${facts[s[1]]}</p></details>`:''}<div class="tags">${s[4].map(t=>`<span>${t}</span>`).join('')}</div><a class="map-link" target="_blank" rel="noreferrer" href="${navigate(s[2])}">導航至此處</a></article>`).join('');$('#logistics').innerHTML=d.notes.map(x=>`<p>• ${x}</p>`).join('');window.scrollTo({top:0,behavior:'smooth'})}
$('.days').innerHTML=days.map((d,i)=>`<button class="day-btn" aria-selected="${i===0}" data-day="${i}" aria-label="第 ${i+1} 天，${d.date}">第 ${i+1} 天<strong>${d.date.slice(0,4)}</strong></button>`).join('');document.querySelectorAll('.day-btn').forEach(b=>b.addEventListener('click',()=>render(+b.dataset.day)));render(0);
const gallery={'吉野家 鰻重':['https://www.ssnp.co.jp/uploads/previous/news/foodservice/2021/04/images/210422yoshinoya1.jpg','https://cdn.macaro-ni.jp/image/summary/156/156106/E7HFoairRQyzXCfhrGMkZ0ACxM0iu570QSRv7nUy.jpg'],'燒肉 金城':['https://tblg.k-img.com/restaurant/images/Rvw/188903/640x640_rect_184cea9f36df7934cc4cf613edbcdc5a.jpg','https://stat.ameba.jp/user_images/20211113/09/tappy-2020/a6/77/j/o1080081015030630504.jpg'],'備瀨福木林道':['https://www.japanican.com/wp-content/uploads/2023/04/okinawa_Fukugi-trees-in-Bise_110212.jpg','https://assets.japantravel.com/photo/5798-39004/1200x630%21/okinawa-bise-village-okinawa-39004.jpg'],'古宇利島':['https://www.knt.co.jp/meito/images/korijima_mv.jpg','https://d340eiag32bpum.cloudfront.net/img/post/article/1722/172137-yCCPfCmD0qwMkUGSTtmN_lrg_sq.jpg']};new MutationObserver(()=>document.querySelectorAll('.feature').forEach(card=>{const name=card.querySelector('h3')?.childNodes[0]?.textContent?.trim();if(gallery[name]&&!card.querySelector('.photo-strip')){const strip=document.createElement('div');strip.className='photo-strip';strip.innerHTML=gallery[name].map((src,i)=>`<img src="${src}" alt="${name} 實景照片 ${i+1}" loading="lazy">`).join('');card.prepend(strip)}})).observe(document.querySelector('#features'),{childList:true});
render(0);
Object.keys(photos).forEach(k=>delete photos[k]);Object.assign(gallery,{
  '美麗海水族館':['media/aquarium-1.jpg','media/aquarium-2.jpg','media/aquarium-3.jpg','media/aquarium-4.jpg'],
  '備瀨福木林道':['media/bise-1.jpg','media/bise-2.jpg','media/bise-3.jpg','media/bise-4.jpg'],
  '古宇利島':['media/kouri-1.jpg','media/kouri-3.jpg'],
  '首里城公園':['media/shuri-1.jpg'],
  '吉野家 鰻重':['media/food-yoshinoya.jpg','media/food-yoshinoya-2.jpg'],
  '燒肉 金城':['media/food-kinjo-food-2.jpg']
});render(0);
function render(i){const d=days[i],mapImage=`media/map-day${i+1}-clean.png`;document.querySelectorAll('.day-btn').forEach((b,n)=>b.setAttribute('aria-selected',n===i));$('#folio').textContent=d.date;$('#dayTitle').textContent=d.title;$('#dayTheme').textContent=d.theme;$('#lede').textContent=d.lede;$('#map').innerHTML=`<img class="route-map" src="${mapImage}" alt="第 ${i+1} 天，${d.map} 行車路線圖"><div class="map-title"><span>今日行車路線</span><strong>${d.map}</strong></div>`;$('#features').innerHTML=d.stops.map((s,n)=>`<article class="feature">${photos[s[1]]?`<img class="spot-photo" src="${photos[s[1]]}" alt="${s[1]} 實景照片">`:''}<div class="feature-meta"><span>${s[0]}</span><span>第 ${n+1} 站</span></div><h3>${s[1]}<small>${s[2]}</small></h3><p>${s[3]}</p>${facts[s[1]]?`<details class="more"><summary>歷史與特色</summary><p>${facts[s[1]]}</p></details>`:''}<div class="tags">${s[4].map(t=>`<span>${t}</span>`).join('')}</div><a class="map-link" target="_blank" rel="noreferrer" href="${navigate(s[2])}">導航至此處</a></article>`).join('');$('#logistics').innerHTML=d.notes.map(x=>`<p>• ${x}</p>`).join('');window.scrollTo({top:0,behavior:'smooth'})}
Object.assign(gallery,{
  '吉野家 鰻重':['media/trip-photos/吉野家/images.jpg','media/trip-photos/吉野家/images (1).jpg'],
  '美麗海水族館':['media/trip-photos/美海水族館/images.jpg','media/trip-photos/美海水族館/images (1).jpg','media/trip-photos/美海水族館/20250828okinawaaquariumgaikan01-860x500-1756369439.webp','media/trip-photos/美海水族館/20250828okinawaaquarium03-860x500-1756365812.webp'],
  '備瀨福木林道':['media/trip-photos/福木林道/福木9.jpg','media/trip-photos/福木林道/images.jpg'],
  '古宇利島':['media/trip-photos/古宇利島/kouri_okinawa6-2.webp','media/trip-photos/古宇利島/kourioohashi03-1000x667-1776223399.webp','media/trip-photos/古宇利島/2604kouri2-870x500-1776067396.webp','media/trip-photos/古宇利島/20250320_184912_608e1329_w1920.webp','media/trip-photos/古宇利島/20231107_150618_fa5d52e8_w1920.webp'],
  '燒肉 金城':['media/trip-photos/燒肉金城/0004038670F3.jpg','media/trip-photos/燒肉金城/yakiniku-kinjo-okinawa-42.jpg','media/trip-photos/燒肉金城/640x640_rect_8810077bb1763f77422240c8e3ee67e7.jpg'],
  '齋場御嶽':['media/trip-photos/齋場御嶽/IMG_7617-780x585.jpg','media/trip-photos/齋場御嶽/di144_kv_sefa-utaki-sacred-grounds.webp','media/trip-photos/齋場御嶽/di144_01_sefa-utaki-sangui.webp','media/trip-photos/齋場御嶽/20210220113228_1.jpg'],
  '首里城公園':['media/trip-photos/首里城公園/shuri-castle01JPG_2019-08-28 22_18_50.JPG','media/trip-photos/首里城公園/images.jpg','media/trip-photos/首里城公園/images (1).jpg','media/trip-photos/首里城公園/di146_01_shurijo-castle-exterior.webp','media/trip-photos/首里城公園/20230724_141243_c19f3536_w1920.webp'],
  '瀨長島':['media/trip-photos/賴長島/SenakaIsland_05-860x500-1756280015.webp','media/trip-photos/賴長島/SenakaIsland_04-860x500-1756279414.webp','media/trip-photos/賴長島/SenakaIsland_03-870x500-1756279185.webp','media/trip-photos/賴長島/1525687830-4a4809e99fbfe26f36f82bad0382e058.jpg'],
  'Jack’s Steak House':["media/trip-photos/Jack's Steak House/oki2005_32.jpg","media/trip-photos/Jack's Steak House/images.jpg","media/trip-photos/Jack's Steak House/images (1).jpg","media/trip-photos/Jack's Steak House/images (2).jpg"],
  'そば處 玉家':['media/trip-photos/SOBA處 玉家/640x640_rect_10423618.jpg','media/trip-photos/SOBA處 玉家/20260526_153810_00e366f8_w1920.webp']
});render(0);
